/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ThoughtId = IDL.Nat;
export const ConnectionId = IDL.Nat;
export const Connection = IDL.Record({
  'id' : ConnectionId,
  'toId' : ThoughtId,
  'fromId' : ThoughtId,
});
export const CreateThoughtArgs = IDL.Record({
  'tag' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
});
export const Thought = IDL.Record({
  'id' : ThoughtId,
  'tag' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'clearAll' : IDL.Func([], [], []),
  'createConnection' : IDL.Func([ThoughtId, ThoughtId], [Connection], []),
  'createThought' : IDL.Func([CreateThoughtArgs], [Thought], []),
  'deleteConnection' : IDL.Func([ConnectionId], [], []),
  'deleteThought' : IDL.Func([ThoughtId], [], []),
  'getThought' : IDL.Func([ThoughtId], [IDL.Opt(Thought)], ['query']),
  'listConnections' : IDL.Func([], [IDL.Vec(Connection)], ['query']),
  'listThoughts' : IDL.Func([], [IDL.Vec(Thought)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ThoughtId = IDL.Nat;
  const ConnectionId = IDL.Nat;
  const Connection = IDL.Record({
    'id' : ConnectionId,
    'toId' : ThoughtId,
    'fromId' : ThoughtId,
  });
  const CreateThoughtArgs = IDL.Record({
    'tag' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
  });
  const Thought = IDL.Record({
    'id' : ThoughtId,
    'tag' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'clearAll' : IDL.Func([], [], []),
    'createConnection' : IDL.Func([ThoughtId, ThoughtId], [Connection], []),
    'createThought' : IDL.Func([CreateThoughtArgs], [Thought], []),
    'deleteConnection' : IDL.Func([ConnectionId], [], []),
    'deleteThought' : IDL.Func([ThoughtId], [], []),
    'getThought' : IDL.Func([ThoughtId], [IDL.Opt(Thought)], ['query']),
    'listConnections' : IDL.Func([], [IDL.Vec(Connection)], ['query']),
    'listThoughts' : IDL.Func([], [IDL.Vec(Thought)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };