/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ConnectionId = bigint;
export type ThoughtId = bigint;
export interface CreateThoughtArgs {
    tag?: string;
    title: string;
    description?: string;
}
export interface Connection {
    id: ConnectionId;
    toId: ThoughtId;
    fromId: ThoughtId;
}
export interface Thought {
    id: ThoughtId;
    tag?: string;
    title: string;
    createdAt: bigint;
    description?: string;
}
export interface backendInterface {
    clearAll(): Promise<void>;
    createConnection(fromId: ThoughtId, toId: ThoughtId): Promise<Connection>;
    createThought(args: CreateThoughtArgs): Promise<Thought>;
    deleteConnection(id: ConnectionId): Promise<void>;
    deleteThought(id: ThoughtId): Promise<void>;
    getThought(id: ThoughtId): Promise<Thought | null>;
    listConnections(): Promise<Array<Connection>>;
    listThoughts(): Promise<Array<Thought>>;
}
import type { CreateThoughtArgs as _CreateThoughtArgs, Thought as _Thought, ThoughtId as _ThoughtId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearAll(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAll();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAll();
            return result;
        }
    }
    async createConnection(arg0: ThoughtId, arg1: ThoughtId): Promise<Connection> {
        if (this.processError) {
            try {
                const result = await this.actor.createConnection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConnection(arg0, arg1);
            return result;
        }
    }
    async createThought(arg0: CreateThoughtArgs): Promise<Thought> {
        if (this.processError) {
            try {
                const result = await this.actor.createThought(to_candid_CreateThoughtArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Thought_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createThought(to_candid_CreateThoughtArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Thought_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteConnection(arg0: ConnectionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConnection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConnection(arg0);
            return result;
        }
    }
    async deleteThought(arg0: ThoughtId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteThought(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteThought(arg0);
            return result;
        }
    }
    async getThought(arg0: ThoughtId): Promise<Thought | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getThought(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThought(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async listConnections(): Promise<Array<Connection>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConnections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConnections();
            return result;
        }
    }
    async listThoughts(): Promise<Array<Thought>> {
        if (this.processError) {
            try {
                const result = await this.actor.listThoughts();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listThoughts();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Thought_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Thought): Thought {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Thought]): Thought | null {
    return value.length === 0 ? null : from_candid_Thought_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ThoughtId;
    tag: [] | [string];
    title: string;
    createdAt: bigint;
    description: [] | [string];
}): {
    id: ThoughtId;
    tag?: string;
    title: string;
    createdAt: bigint;
    description?: string;
} {
    return {
        id: value.id,
        tag: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.tag)),
        title: value.title,
        createdAt: value.createdAt,
        description: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.description))
    };
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Thought>): Array<Thought> {
    return value.map((x)=>from_candid_Thought_n3(_uploadFile, _downloadFile, x));
}
function to_candid_CreateThoughtArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateThoughtArgs): _CreateThoughtArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tag?: string;
    title: string;
    description?: string;
}): {
    tag: [] | [string];
    title: string;
    description: [] | [string];
} {
    return {
        tag: value.tag ? candid_some(value.tag) : candid_none(),
        title: value.title,
        description: value.description ? candid_some(value.description) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
